[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Edin <edin.omeragic@gmail.com>", "Darley <darleybarreto@gmail.com>"]

[[bin]]
path = "./src/ray_tracer.rs"
name = "ray_tracer"

[dependencies]
bmp = "0.5.0"
rayon = "1.5.0"